# Generated by Django 2.2.5 on 2019-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_somthing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
